# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aidenchia/Desktop/MQF/C++/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aidenchia/Desktop/MQF/C++/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidenchia/Desktop/MQF/C++/project/CMakeFiles /Users/aidenchia/Desktop/MQF/C++/project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidenchia/Desktop/MQF/C++/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named step1

# Build rule for target.
step1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step1 CXXFLAGS="-g"
.PHONY : step1

# fast build rule for target.
step1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/build
.PHONY : step1/fast

#=============================================================================
# Target rules for targets named step2

# Build rule for target.
step2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step2 CXXFLAGS="-g"
.PHONY : step2

# fast build rule for target.
step2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/build
.PHONY : step2/fast

#=============================================================================
# Target rules for targets named step3

# Build rule for target.
step3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 step3 CXXFLAGS="-g"
.PHONY : step3

# fast build rule for target.
step3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/build
.PHONY : step3/fast

#=============================================================================
# Target rules for targets named test_lbfgs

# Build rule for target.
test_lbfgs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lbfgs
.PHONY : test_lbfgs

# fast build rule for target.
test_lbfgs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/build
.PHONY : test_lbfgs/fast

#=============================================================================
# Target rules for targets named test_ts_parser

# Build rule for target.
test_ts_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ts_parser
.PHONY : test_ts_parser

# fast build rule for target.
test_ts_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/build
.PHONY : test_ts_parser/fast

CsvFeeder.o: CsvFeeder.cpp.o
.PHONY : CsvFeeder.o

# target to build an object file
CsvFeeder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/CsvFeeder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/CsvFeeder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CsvFeeder.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/CsvFeeder.cpp.o
.PHONY : CsvFeeder.cpp.o

CsvFeeder.i: CsvFeeder.cpp.i
.PHONY : CsvFeeder.i

# target to preprocess a source file
CsvFeeder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/CsvFeeder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/CsvFeeder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CsvFeeder.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/CsvFeeder.cpp.i
.PHONY : CsvFeeder.cpp.i

CsvFeeder.s: CsvFeeder.cpp.s
.PHONY : CsvFeeder.s

# target to generate assembly for a file
CsvFeeder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/CsvFeeder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/CsvFeeder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CsvFeeder.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/CsvFeeder.cpp.s
.PHONY : CsvFeeder.cpp.s

CubicSmile.o: CubicSmile.cpp.o
.PHONY : CubicSmile.o

# target to build an object file
CubicSmile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CubicSmile.cpp.o
.PHONY : CubicSmile.cpp.o

CubicSmile.i: CubicSmile.cpp.i
.PHONY : CubicSmile.i

# target to preprocess a source file
CubicSmile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CubicSmile.cpp.i
.PHONY : CubicSmile.cpp.i

CubicSmile.s: CubicSmile.cpp.s
.PHONY : CubicSmile.s

# target to generate assembly for a file
CubicSmile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/CubicSmile.cpp.s
.PHONY : CubicSmile.cpp.s

Date.o: Date.cpp.o
.PHONY : Date.o

# target to build an object file
Date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/Date.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/Date.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/Date.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/Date.cpp.o
.PHONY : Date.cpp.o

Date.i: Date.cpp.i
.PHONY : Date.i

# target to preprocess a source file
Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/Date.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/Date.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/Date.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/Date.cpp.i
.PHONY : Date.cpp.i

Date.s: Date.cpp.s
.PHONY : Date.s

# target to generate assembly for a file
Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/Date.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/Date.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/Date.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/Date.cpp.s
.PHONY : Date.cpp.s

Solver/LBFGSpp/examples/example-rosenbrock-box.o: Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.o
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.o

# target to build an object file
Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.o
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.o

Solver/LBFGSpp/examples/example-rosenbrock-box.i: Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.i
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.i

# target to preprocess a source file
Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.i
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.i

Solver/LBFGSpp/examples/example-rosenbrock-box.s: Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.s
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.s

# target to generate assembly for a file
Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lbfgs.dir/build.make CMakeFiles/test_lbfgs.dir/Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.s
.PHONY : Solver/LBFGSpp/examples/example-rosenbrock-box.cpp.s

step1.o: step1.cpp.o
.PHONY : step1.o

# target to build an object file
step1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/step1.cpp.o
.PHONY : step1.cpp.o

step1.i: step1.cpp.i
.PHONY : step1.i

# target to preprocess a source file
step1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/step1.cpp.i
.PHONY : step1.cpp.i

step1.s: step1.cpp.s
.PHONY : step1.s

# target to generate assembly for a file
step1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step1.dir/build.make CMakeFiles/step1.dir/step1.cpp.s
.PHONY : step1.cpp.s

step2.o: step2.cpp.o
.PHONY : step2.o

# target to build an object file
step2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/step2.cpp.o
.PHONY : step2.cpp.o

step2.i: step2.cpp.i
.PHONY : step2.i

# target to preprocess a source file
step2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/step2.cpp.i
.PHONY : step2.cpp.i

step2.s: step2.cpp.s
.PHONY : step2.s

# target to generate assembly for a file
step2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step2.dir/build.make CMakeFiles/step2.dir/step2.cpp.s
.PHONY : step2.cpp.s

step3.o: step3.cpp.o
.PHONY : step3.o

# target to build an object file
step3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/step3.cpp.o
.PHONY : step3.cpp.o

step3.i: step3.cpp.i
.PHONY : step3.i

# target to preprocess a source file
step3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/step3.cpp.i
.PHONY : step3.cpp.i

step3.s: step3.cpp.s
.PHONY : step3.s

# target to generate assembly for a file
step3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/step3.dir/build.make CMakeFiles/step3.dir/step3.cpp.s
.PHONY : step3.cpp.s

test_ts_parser.o: test_ts_parser.cpp.o
.PHONY : test_ts_parser.o

# target to build an object file
test_ts_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/test_ts_parser.cpp.o
.PHONY : test_ts_parser.cpp.o

test_ts_parser.i: test_ts_parser.cpp.i
.PHONY : test_ts_parser.i

# target to preprocess a source file
test_ts_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/test_ts_parser.cpp.i
.PHONY : test_ts_parser.cpp.i

test_ts_parser.s: test_ts_parser.cpp.s
.PHONY : test_ts_parser.s

# target to generate assembly for a file
test_ts_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ts_parser.dir/build.make CMakeFiles/test_ts_parser.dir/test_ts_parser.cpp.s
.PHONY : test_ts_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... step1"
	@echo "... step2"
	@echo "... step3"
	@echo "... test_lbfgs"
	@echo "... test_ts_parser"
	@echo "... CsvFeeder.o"
	@echo "... CsvFeeder.i"
	@echo "... CsvFeeder.s"
	@echo "... CubicSmile.o"
	@echo "... CubicSmile.i"
	@echo "... CubicSmile.s"
	@echo "... Date.o"
	@echo "... Date.i"
	@echo "... Date.s"
	@echo "... Solver/LBFGSpp/examples/example-rosenbrock-box.o"
	@echo "... Solver/LBFGSpp/examples/example-rosenbrock-box.i"
	@echo "... Solver/LBFGSpp/examples/example-rosenbrock-box.s"
	@echo "... step1.o"
	@echo "... step1.i"
	@echo "... step1.s"
	@echo "... step2.o"
	@echo "... step2.i"
	@echo "... step2.s"
	@echo "... step3.o"
	@echo "... step3.i"
	@echo "... step3.s"
	@echo "... test_ts_parser.o"
	@echo "... test_ts_parser.i"
	@echo "... test_ts_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

